# Generated by Django 5.2.3 on 2025-07-02 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='money_per_click',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='money_per_second',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='time_money_last_earn',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 2, 16, 25, 24, 94891, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
