# Generated by Django 5.2.3 on 2025-07-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_money_per_click_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_item_time',
            new_name='last_shop_update_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='money_per_click',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='money_per_second',
        ),
    ]
