# Generated by Django 5.2.3 on 2025-07-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_email_alter_customuser_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_shop_update_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
