# Generated by Django 5.2.3 on 2025-07-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_last_shop_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='money_per_click',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='money_per_second',
            field=models.BigIntegerField(default=0),
        ),
    ]
