# Generated by Django 5.2.3 on 2025-07-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_money_per_click_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verfication_token_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(null=True),
        ),
    ]
