# Generated by Django 5.2.3 on 2025-07-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verfication_token_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(null=True),
        ),
    ]
