# Generated by Django 5.2.3 on 2025-07-03 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FieldItems',
            new_name='ShopItem',
        ),
        migrations.AddField(
            model_name='items',
            name='addition_factor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='multiplication_factor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='items',
            name='cost',
            field=models.CharField(),
        ),
        migrations.CreateModel(
            name='AuctionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Baskets',
        ),
    ]
