# Generated by Django 5.2.3 on 2025-07-03 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_rename_fielditems_shopitem_items_addition_factor_and_more"),
    ]
