# Generated by Django 5.2.3 on 2025-07-05 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_rename_addition_factor_items_click_factor_and_more"),
    ]
